name: Dunolint Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  dunolint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install dunolint
        uses: mbarbin/dunolint-actions/setup-dunolint@6b1c0591ba857063829211bc162712052889c4e2 # v1.0.0-alpha.4
        with:
          dunolint-version: 0.0.20260211
          dunolint-digest: sha256:8ce2817547a7b104b677e89baf6e6fcb8805811172ae9557505bdd866ee16fbc

      - name: Lint Check
        uses: mbarbin/dunolint-actions/lint-check@6b1c0591ba857063829211bc162712052889c4e2 # v1.0.0-alpha.4
